from django.conf.urls import *
from django.contrib import admin
from views import index_view, choose_faction, registration, registrationComplete, login, loginComplete, city, world, playerAction, intendency, intendencyUpgrade, intendencyWorkers, intendencyWorkersComplete, sawmill, sawmillUpgrade, mines, minesUpgrade, farm, farmUpgrade, deposit, depositUpgrade, wall, wallUpgrade, barrack, barrackUpgrade, barrackArmy, barrackArmy2, barrackArmy2Complete, attack, attackComplete, trade, trade2, trade2Complete, messages, messagesOutbox, messagesOutbox2, messagesInbox, messagesInbox2, messagesSend, messagesSendComplete, reports, reportsBattle, reportsBattle2, reportsTrade, reportsTrade2, ranking
from django.conf.urls import include, url

urlpatterns = patterns('',
	url(r'^$', index_view),
	url(r'^accounts/choose_faction/$', choose_faction),
	url(r'^accounts/registration/$', registration),
	url(r'^accounts/registrationComplete/$', registrationComplete),
	url(r'^accounts/login/$', login),
	url(r'^accounts/loginComplete/$', loginComplete),
	url(r'^game/city/$', city),
	url(r'^game/world/$', world),
	url(r'^game/playerAction/(?P<id>\d+)$', playerAction),
	url(r'^game/build/intendency/$', intendency),
	url(r'^game/build/intendency/upgrade/$', intendencyUpgrade),
	url(r'^game/build/intendency/workers/$', intendencyWorkers),
	url(r'^game/build/intendency/workersComplete/$', intendencyWorkersComplete),
	url(r'^game/build/sawmill/$', sawmill),
	url(r'^game/build/sawmill/upgrade/$', sawmillUpgrade),
	url(r'^game/build/mine/$', mines),
	url(r'^game/build/mine/upgrade/$', minesUpgrade),
	url(r'^game/build/farm/$', farm),
	url(r'^game/build/farm/upgrade/$', farmUpgrade),
	url(r'^game/build/deposit/$', deposit),
	url(r'^game/build/deposit/upgrade/$', depositUpgrade),
	url(r'^game/build/wall/$', wall),
	url(r'^game/build/wall/upgrade/$', wallUpgrade),
	url(r'^game/build/barrack/$', barrack),
	url(r'^game/build/barrack/upgrade/$', barrackUpgrade),
	url(r'^game/build/barrack/army/$', barrackArmy),
	url(r'^game/build/barrack/army2/(?P<id>\d+)$', barrackArmy2),
	url(r'^game/build/barrack/army2Complete/$', barrackArmy2Complete),
	url(r'^game/attack/$', attack),
	url(r'^game/attackComplete/$', attackComplete),
	url(r'^game/trade/$', trade),
	url(r'^game/trade2/$', trade2),
	url(r'^game/trade2Complete/$', trade2Complete),
	url(r'^game/messages/$', messages),
	url(r'^game/messages/outbox/$', messagesOutbox),
	url(r'^game/messages/outbox2/(?P<id>\d+)$', messagesOutbox2),
	url(r'^game/messages/inbox/$', messagesInbox),
	url(r'^game/messages/inbox2/(?P<id>\d+)$', messagesInbox2),
	url(r'^game/messages/send/$', messagesSend),
	url(r'^game/messages/sendComplete/$', messagesSendComplete),
	url(r'^game/reports/$', reports),
	url(r'^game/reports/battle/$', reportsBattle),
	url(r'^game/reports/battle2/(?P<id>\d+)$', reportsBattle2),
	url(r'^game/reports/trade/$', reportsTrade),
	url(r'^game/reports/trade2/(?P<id>\d+)$', reportsTrade2),
	url(r'^game/ranking/$', ranking),
)

